version: '3'

services:

    registry:
#      restart: always
      image: registry:2
      ports:
        - 5000:5000
      hostname: "registry"
          networks:
            - test
      environment:
          REGISTRY_HTTP_TLS_CERTIFICATE: /certs/ssl_certificate.cer
          REGISTRY_HTTP_TLS_KEY: /certs/sprinklebit.com.key
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      volumes:
        - ./data:/var/lib/registry
        - ./auth:/auth
        - ./certs:/certs

networks:
  test:
    external:
      name: test